"""Generates deploy/notebook.ipynb - the Kaggle deployment notebook for this repo.

Run from the repo root:  python deploy/create_nb.py
"""

import json

REPO_URL = "https://github.com/yashNiwane/orato-asr-server.git"

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Orato ASR Server v2 (vLLM on T4)\n",
                "\n",
                "Clones **this** repository (`orato-asr-server`), loads Qwen3-ASR through the vLLM backend\n",
                "and exposes realtime WebSocket + REST transcription via a free Cloudflare quick tunnel.\n",
                "\n",
                "**v2 highlights**\n",
                "- No native-streaming path: partials use windowed re-decode (the v1 native path could hang the CUDA worker).\n",
                "- GPU watchdog: any decode exceeding `DECODE_TIMEOUT_SEC` fails fast with an `error` event and exits(70).\n",
                "- **Supervised auto-restart**: this notebook restarts the server automatically if it crashes or wedges - the tunnel URL stays valid.\n",
                "- Direct PCM16 WS intake, telecalling-tuned turn-taking (150ms partials / 400ms finals).\n",
                "\n",
                "**Requirements**\n",
                "- Kaggle accelerator: **GPU T4 x2** (vLLM needs compute capability >= 7.0).\n",
                "- Kaggle Secret named **`HF_TOKEN`** (*Add-ons -> Secrets*). Never hardcode tokens.\n",
                "- Quick-tunnel URLs change between sessions; read the fresh URL from this output."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 1: Install core GPU inference stack\n",
                "!pip install -q -U \"qwen-asr[vllm]\"\n",
                "!pip show qwen-asr vllm | grep -E \"^(Name|Version):\"\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 2: Clone this repository and install its pinned deps\n",
                "REPO_URL = '%s'\n",
                "REPO_DIR = '/kaggle/working/asr-server'\n",
                "!rm -rf {REPO_DIR}\n",
                "!git clone {REPO_URL} {REPO_DIR}\n",
                "%cd {REPO_DIR}\n",
                "!git log --oneline -1\n",
                "!pip install -q -r requirements.txt\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 3: Environment configuration\n",
                "import os\n",
                "\n",
                "def _get_hf_token() -> str:\n",
                "    try:\n",
                "        from kaggle_secrets import UserSecretsClient\n",
                "        token = UserSecretsClient().get_secret('HF_TOKEN')\n",
                "        if token and token.strip():\n",
                "            return token.strip()\n",
                "    except Exception:\n",
                "        pass\n",
                "    raise RuntimeError(\n",
                "        \"Missing Kaggle Secret 'HF_TOKEN'.\\n\"\n",
                "        \"Add it via Add-ons -> Secrets -> Add a secret (label: HF_TOKEN), then re-run.\"\n",
                "    )\n",
                "\n",
                "_hf_token = _get_hf_token()\n",
                "os.environ['HF_TOKEN'] = _hf_token\n",
                "os.environ['HUGGING_FACE_HUB_TOKEN'] = _hf_token\n",
                "print('[+] HF_TOKEN loaded from Kaggle Secrets')\n",
                "\n",
                "# Model / backend\n",
                "os.environ['ASR_MODEL'] = 'Qwen/Qwen3-ASR-0.6B'   # or tryorato/orato-asr-hindi-v1 fine-tune\n",
                "os.environ['DEVICE'] = 'cuda'\n",
                "os.environ['ASR_BACKEND'] = 'vllm'\n",
                "os.environ['CUDA_VISIBLE_DEVICES'] = '0'          # pin first T4\n",
                "os.environ['TORCH_CUDA_ARCH_LIST'] = '7.5'        # T4-only JIT targets (faster startup)\n",
                "os.environ['VLLM_GPU_MEMORY_UTILIZATION'] = '0.85'\n",
                "os.environ['TOKENIZERS_PARALLELISM'] = 'false'\n",
                "\n",
                "# Reliability (see README): watchdog ceiling per GPU submission.\n",
                "os.environ['DECODE_TIMEOUT_SEC'] = '20'\n",
                "\n",
                "# Streaming cadence - v2 defaults are already telecalling-tuned;\n",
                "# uncomment to override:\n",
                "# os.environ['STREAM_CHUNK_DURATION'] = '0.15'\n",
                "# os.environ['SILENCE_DURATION_FLUSH'] = '0.4'\n",
                "\n",
                "print('[+] Configuration complete')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 4: Verify GPU + fix FlashInfer JIT linking\n",
                "import os\n",
                "import glob\n",
                "import subprocess\n",
                "\n",
                "import torch\n",
                "\n",
                "print('CUDA Available:', torch.cuda.is_available())\n",
                "if torch.cuda.is_available():\n",
                "    print('GPU Device:', torch.cuda.get_device_name(0))\n",
                "    cc = torch.cuda.get_device_capability(0)\n",
                "    print('Compute Capability:', cc)\n",
                "    assert cc >= (7, 0), 'vLLM requires T4 or newer. Switch the accelerator to GPU T4 x2!'\n",
                "    import vllm\n",
                "    print('vLLM version:', vllm.__version__)\n",
                "\n",
                "def _find_libcuda():\n",
                "    out = subprocess.run('ldconfig -p', shell=True, capture_output=True, text=True).stdout\n",
                "    for line in out.splitlines():\n",
                "        if '/libcuda.so' in line:\n",
                "            return line.split('=>')[-1].strip()\n",
                "    for pattern in ['/usr/lib/x86_64-linux-gnu/**/libcuda.so*', '/usr/local/nvidia/**/libcuda.so*']:\n",
                "        hits = sorted(glob.glob(pattern, recursive=True))\n",
                "        if hits:\n",
                "            return hits[0]\n",
                "    return None\n",
                "\n",
                "src = _find_libcuda()\n",
                "if src:\n",
                "    targets = [\n",
                "        '/usr/lib/x86_64-linux-gnu/libcuda.so',\n",
                "        os.path.join(os.path.dirname(src), 'libcuda.so'),\n",
                "    ]\n",
                "    src_dir = os.path.dirname(src)\n",
                "    for t in targets:\n",
                "        try:\n",
                "            if not os.path.exists(t):\n",
                "                subprocess.run(\n",
                "                    f'sudo mkdir -p \"{os.path.dirname(t)}\" && sudo ln -sf \"{src}\" \"{t}\"',\n",
                "                    shell=True, check=True,\n",
                "                )\n",
                "        except Exception as e:\n",
                "            print(f'[!] Skipped {t}: {e}')\n",
                "    os.environ['LIBRARY_PATH'] = (\n",
                "        f'{src_dir}:/usr/local/cuda/lib64/stubs:' + os.environ.get('LIBRARY_PATH', '')\n",
                "    )\n",
                "    print(f'[+] libcuda.so -> {src}')\n",
                "else:\n",
                "    print('[!] Could not locate libcuda driver library')\n",
                "subprocess.run('sudo ldconfig', shell=True)\n",
                "\n",
                "probe = subprocess.run(\n",
                "    'echo \"int main(){return 0;}\" > /tmp/_lc.c && gcc /tmp/_lc.c -lcuda -o /tmp/_lc.bin',\n",
                "    shell=True, capture_output=True, text=True,\n",
                ")\n",
                "print('[+] Linker check:', '-lcuda OK' if probe.returncode == 0 else f'STILL BROKEN:\\n{probe.stderr}')\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 5: Cloudflare tunnel + supervised server (auto-restart on crash/wedge)\n",
                "import json\n",
                "import re\n",
                "import subprocess\n",
                "import time\n",
                "import urllib.request\n",
                "from pathlib import Path\n",
                "\n",
                "PORT = 8000\n",
                "LOG_PATH = '/kaggle/working/server.log'\n",
                "CLOUDFLARED = '/kaggle/working/cloudflared'\n",
                "MAX_RESTARTS = 8\n",
                "\n",
                "if not Path(CLOUDFLARED).exists():\n",
                "    subprocess.run([\n",
                "        'wget', '-q',\n",
                "        'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64',\n",
                "        '-O', CLOUDFLARED,\n",
                "    ], check=True)\n",
                "    Path(CLOUDFLARED).chmod(0o755)\n",
                "\n",
                "# --- Tunnel (started once; survives server restarts so the URL stays stable) ---\n",
                "def start_tunnel(max_attempts: int = 3):\n",
                "    for attempt in range(1, max_attempts + 1):\n",
                "        proc = subprocess.Popen(\n",
                "            [CLOUDFLARED, 'tunnel', '--url', f'http://localhost:{PORT}', '--no-autoupdate'],\n",
                "            stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True,\n",
                "        )\n",
                "        deadline = time.time() + 60\n",
                "        while time.time() < deadline:\n",
                "            line = proc.stdout.readline()\n",
                "            if not line:\n",
                "                time.sleep(0.2)\n",
                "                continue\n",
                "            match = re.search(r'https://[a-z0-9-]+\\.trycloudflare\\.com', line)\n",
                "            if match:\n",
                "                return proc, match.group(0)\n",
                "        proc.terminate()\n",
                "        print(f'[!] Tunnel attempt {attempt} failed, retrying...')\n",
                "        time.sleep(3)\n",
                "    raise RuntimeError('Cloudflare tunnel failed after retries. Re-run this cell.')\n",
                "\n",
                "tunnel, public_url = start_tunnel()\n",
                "ws_url = public_url.replace('https', 'wss') + '/ws/transcribe?language=Hindi'\n",
                "print(f'[+] Tunnel up: {public_url}')\n",
                "\n",
                "log_handle = open(LOG_PATH, 'a', buffering=1)\n",
                "\n",
                "def spawn_server():\n",
                "    return subprocess.Popen(\n",
                "        ['python', '-m', 'uvicorn', 'app.server:app',\n",
                "         '--host', '0.0.0.0', '--port', str(PORT),\n",
                "         '--ws-ping-interval', '20', '--ws-ping-timeout', '60'],\n",
                "        stdout=log_handle, stderr=subprocess.STDOUT,\n",
                "    )\n",
                "\n",
                "def wait_ready(proc, timeout_sec: float = 1200) -> bool:\n",
                "    \"\"\"Poll /health until the engine is ready (or the process dies).\"\"\"\n",
                "    deadline = time.time() + timeout_sec\n",
                "    while time.time() < deadline:\n",
                "        if proc.poll() is not None:\n",
                "            return False\n",
                "        try:\n",
                "            with urllib.request.urlopen(f'http://127.0.0.1:{PORT}/health', timeout=5) as resp:\n",
                "                info = json.loads(resp.read().decode())\n",
                "            if info.get('is_ready'):\n",
                "                print(f\"[+] Engine ready: backend={info.get('backend')} device={info.get('device')}\")\n",
                "                return True\n",
                "        except Exception:\n",
                "            pass\n",
                "        time.sleep(5)\n",
                "    return False\n",
                "\n",
                "def gpu_mem():\n",
                "    return subprocess.run(\n",
                "        ['nvidia-smi', '--query-gpu=memory.used,memory.total', '--format=csv,noheader'],\n",
                "        capture_output=True, text=True,\n",
                "    ).stdout.strip()\n",
                "\n",
                "restarts = 0\n",
                "server = spawn_server()\n",
                "banner_shown = False\n",
                "try:\n",
                "    while True:\n",
                "        print(f'[+] Server pid {server.pid} loading model (logs: {LOG_PATH})...')\n",
                "        if not wait_ready(server):\n",
                "            code = server.returncode\n",
                "            if code is None:\n",
                "                server.terminate()\n",
                "                code = 'not-ready-timeout'\n",
                "            print(f'[!] Server exited during startup (code {code}).')\n",
                "        else:\n",
                "            if not banner_shown:\n",
                "                print('\\n' + '=' * 68)\n",
                "                print('SERVICE READY')\n",
                "                print(f'REST URL : {public_url}')\n",
                "                print(f'WS URL   : {ws_url}')\n",
                "                print('=' * 68 + '\\n')\n",
                "                banner_shown = True\n",
                "            else:\n",
                "                print('[+] Service back up - same URLs.')\n",
                "\n",
                "        # Supervise until the process dies.\n",
                "        started = time.time()\n",
                "        last_beat = time.time()\n",
                "        crashed = True\n",
                "        while server.poll() is None:\n",
                "            time.sleep(5)\n",
                "            if tunnel.poll() is not None:\n",
                "                raise RuntimeError('Tunnel died - a new tunnel gets a NEW URL. Re-run this cell.')\n",
                "            if time.time() - last_beat >= 600 and server.poll() is None:\n",
                "                print(\n",
                "                    f'[heartbeat] up {int((time.time() - started) / 60)} min | '\n",
                "                    f'gpu mem used/total: {gpu_mem()}'\n",
                "                )\n",
                "                last_beat = time.time()\n",
                "\n",
                "        print(f'[!] Server exited (code {server.returncode}).')\n",
                "        restarts += 1\n",
                "        if restarts > MAX_RESTARTS:\n",
                "            raise RuntimeError(f'Restart limit ({MAX_RESTARTS}) exceeded. Check {LOG_PATH}.')\n",
                "        print(f'[!] Auto-restarting server ({restarts}/{MAX_RESTARTS}) in 5s...')\n",
                "        time.sleep(5)\n",
                "        server = spawn_server()\n",
                "finally:\n",
                "    for name in ('server', 'tunnel'):\n",
                "        proc = locals().get(name)\n",
                "        if proc is not None:\n",
                "            try:\n",
                "                proc.terminate()\n",
                "            except Exception:\n",
                "                pass\n",
                "    _log = locals().get('log_handle')\n",
                "    if _log is not None:\n",
                "        _log.close()\n",
                "    print('[+] Cleaned up server and tunnel processes.')\n"
            ]
        }
    ],
    "metadata": {
        "accelerator": "GPU",
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.12"},
    },
    "nbformat": 4,
    "nbformat_minor": 4,
}

with open("deploy/notebook.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)

print("[+] Notebook written to deploy/notebook.ipynb")
